webtalk_init -webtalk_dir C:/Users/JaeWon Kim/Documents/hsd_final_project/28_V0/28_Verilog_V0/term_project_v0.sim/sim_1/behav/xsim/xsim.dir/tb_pe_array_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jun 18 16:02:30 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d803270b-3877-4871-9b0c-6c9b5a9a7e22" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a36ff9af016641c586f3c5497d1b3d3a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "316" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10700T CPU @ 2.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2500 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "27" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.34_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "129620_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3223520497 -regid "" -xml C:/Users/JaeWon Kim/Documents/hsd_final_project/28_V0/28_Verilog_V0/term_project_v0.sim/sim_1/behav/xsim/xsim.dir/tb_pe_array_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/JaeWon Kim/Documents/hsd_final_project/28_V0/28_Verilog_V0/term_project_v0.sim/sim_1/behav/xsim/xsim.dir/tb_pe_array_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/JaeWon Kim/Documents/hsd_final_project/28_V0/28_Verilog_V0/term_project_v0.sim/sim_1/behav/xsim/xsim.dir/tb_pe_array_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
