@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Jun 18 14:30:14 +0900 2021
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim tb_pe_array_behav -key {Behavioral:sim_1:Functional:tb_pe_array} -tclbatch tb_pe_array.tcl -protoinst "protoinst_files/design_1.protoinst" -view C:/Users/JaeWon Kim/Documents/hsd_final_project/28_V0/28_Verilog_V0/tb_my_pe_controller_behav.wcfg -view C:/Users/JaeWon Kim/Documents/hsd_final_project/28_V0/28_Verilog_V0/tb_pe_array_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
